version: '3'
networks:
 campus_virtual:

services:
   ud-observatorio-user:
     image: planesticud/ud-observatorio-user
     container_name: ud-observatorio-user
     restart: on-failure
     env_file:
        - .env
     networks:
        - campus_virtual          

networks:
  campus_virtual:
    external: true